version: '3'
services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8089:3000'
    depends_on:
      - api-rodap-pg

  api-rodap-pg:
    container_name: prisma
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apirodap
